### ISSUE TITLE
Bootstrap*.js files not included when no script used on page

### ISSUE THREAD

**Issue by ShaneCurcuru** [rubys/wunderbar#6]
Already fixed in e8662f9154ce8583bb52533762060e16b510e8d3, but for posterity:

Requiring 'wunderbar/bootstrap' and 'wunderbar/jquery' in a script to be able to use Bootstrap native javascript features (Tooltip, Collapse, etc.) doesn't actually include the JS files if script doesn't have any _script elements in it.

Usercase: I had a simple script creating collapseable sections of content using:
```html
<a role="button" data-toggle="collapse" data-parent="#accordion"... etc.
```
but the _html content emitted didn't us any _script elements of it's own: I only needed the native bootstrap features.  When run, the output didn't include any JS includes, even the expected bootstrap and jquery .js, meaning the Collapse feature didn't work.

Thanks to Sam for fixing so quickly.

**Comment by rubys** [comment]
Fixed: https://github.com/rubys/wunderbar/commit/e8662f9154ce8583bb52533762060e16b510e8d3
